export const designTokens = {
  color: {
    primary: '#5B3A29',
    primaryContainer: '#F1E4D5',
    onPrimary: '#FFFFFF',
    onPrimaryContainer: '#2A170F',
    secondary: '#C5A572',
    secondaryContainer: '#E9D8B9',
    onSecondary: '#241A10',
    onSecondaryContainer: '#3D2B17',
    tertiary: '#8E5639',
    tertiaryContainer: '#F2DDD0',
    onTertiary: '#FFFFFF',
    onTertiaryContainer: '#35190F',
    background: '#FAF7F1',
    surface: '#FFFDF8',
    surfaceVariant: '#F3ECE2',
    surfaceContainer: '#F7F0E7',
    surfaceContainerLow: '#FBF6EF',
    surfaceContainerHigh: '#EFE6DB',
    outline: '#8A7A6B',
    outlineVariant: '#D7C9B8',
    inverseSurface: '#332923',
    inverseOnSurface: '#F8F0E8',
    inversePrimary: '#DAB892',
    textPrimary: '#3C2A1A',
    textSecondary: '#6A5C4E',
    divider: '#E7D6B5',
    error: '#BA1A1A',
    errorContainer: '#FFDAD6',
    onError: '#FFFFFF',
    onErrorContainer: '#410002',
  },
  typography: {
    display: { fontFamily: 'Playfair Display, Georgia, serif', fontWeight: 700 },
    heading: { fontFamily: 'Playfair Display, Georgia, serif', fontWeight: 600 },
    body: { fontFamily: 'Inter, Arial, sans-serif', fontWeight: 400 },
    label: { fontFamily: 'Inter, Arial, sans-serif', fontWeight: 600 },
  },
  spacing: { xs: 4, sm: 8, md: 12, lg: 16, xl: 24, xxl: 32, xxxl: 48 },
  radius: { sm: 8, md: 12, lg: 16, xl: 24, pill: 999 },
  elevation: { none: 'none', low: '0 1px 3px rgba(42, 23, 15, 0.08)', medium: '0 8px 24px rgba(42, 23, 15, 0.12)' },
} as const;

export type DesignTokens = typeof designTokens;
